base:
  mass: 0.02
  size:
    x: 0.095
    y: 0.065
    z: 0.002
  dx: -0.38
  dy: 0.0
  dz: 0.02
  mesh: ''
  scale: 2.5
hub:
  mass: 0.02
  size:
    x: 0.08
    y: 0.06
    z: 0.075
  dx: -0.38
  dy: 0.0
  dz: 0.018
  mesh: ''
  scale: 2.5
wheel:
  mass: 0.5        # Wheel mass in Kg
  radius: 0.025     # Wheel radius in m
  length: 0.03      # Wheel length in m, considering is as a cylinder
  mesh: ''          # Name of the mesh files. Leave it empty ('') to have a red wheel
  x_offset: 0.035
  dx: -0.012  # ${-caster_base_size/2.0*0.8}
  dy: -1
  dz: -0.075
  scale: 2.5