ekf_node:
  ros__parameters: 
    use_sim_time: true
    publish_tf: true
    frame_id: "base_link"
    odom_frame_id: "odom"
    map_frame_id: "map"
    publish_acceleration: false
    publish_twist: true
    publish_odom_tf: true
    odom0: "odom"
    odom0_config: [true, true, false, false, false, false]
    imu0: "imu"
    imu0_config: [false, false, false, true, true, true]
    imu0_differential: false
    imu0_queue_size: 10
